services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/blogdb"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
